### ISSUE TITLE
adaptive-wrap support

### ISSUE THREAD

**Issue by walseb** [jdtsmith/indent-bars#15]
Hello!

The indents created by the [adaptive-wrap](https://elpa.gnu.org/packages/adaptive-wrap.html) package don't have any stripes. 

See screenshot:
![report](https://github.com/jdtsmith/indent-bars/assets/2865774/0ef3fb5d-d723-4e94-b750-70fa466d2e53)

Is it possible to have the stripes continue through the wrapped line? From what I remember of adaptive-wrap, the indents along with the text properties of the space itself is created by the package, so probably this would require modification to adaptive-wrap in some way. But I don't know much of how this package works, so maybe it's just an issue of the precedence of the stripes being too low?

Thanks!

**Comment by jdtsmith** [comment]
I don't use adaptive wrap.  That's all one line?  Does it insert newlines with `'display` or similar?  That will be hard to handle, since font-lock does not match text inside `'display` properties.

**Comment by walseb** [comment]
Hello! 

Thanks so much for looking into this! 

Unfortunately I won't have time to implement something like that for a while, but your analysis is a great start.

**Comment by jdtsmith** [comment]
I took a look and adaptive wrap _should_ inherit the text properties `indent-bars` uses.  In fact, if you remove the `- ` in front of the `lorem ipsum` list item, you see it does actually work fine.  The problem is that `fill-context-prefix` has a small bug or at least a missing feature [here](https://github.com/emacs-mirror/emacs/blob/7b30e11b2ac5cd360db7ee8b6aed07bd918b93a2/lisp/textmodes/fill.el#L312).  If the inferred adaptive prefix is not all space (here it is like `      -`), it is replaced by plain whitespace (no properties).  What it _should_ be replaced by is whitespace with the same string-width and text properties as the line prefix.  

You could report this bug (`M-x report-emacs-bug`) and/or workaround it with a small `adaptive-fill-function`, which replaces the default prefix with "all spaces with correct text properties", e.g. using `fillarray`.
