### ISSUE TITLE
Only show indent bars in current indentation depth?

### ISSUE THREAD

**Issue by gnufied** [jdtsmith/indent-bars#23]
I was wondering if there is a way to ask indent-bars to only show indentation bars for current context. A bit like `highlight-indentation-current-column-mode`

**Comment by jdtsmith** [comment]
I forget how that works, can you show an image?  Are you suggesting to highlight only contiguous bars at the same depth, or only showing any bars at all for some surrounding block?

 indent-bars uses face remapping for ~instant current depth highlight; highlight-indentation is _much_ slower with this, probably because it scans and edits overlays on every keystroke.

**Comment by jdtsmith** [comment]
Or maybe you are asking if it's possible at all.  See `indent-bars-highlight-current-depth`.

**Comment by gnufied** [comment]
Here is what I meant btw -  https://github.com/antonj/Highlight-Indentation-for-Emacs which has `highlight-indentation-current-column-mode` 

I slightly prefer only showing indentation guides for current column because it looks less noisy.  I will check `indent-bars-highlight-current-depth` and see if same thing is possible.

**Comment by jdtsmith** [comment]
That certainly can be achieved: the highlight bar is bright, others are faint.  Just turn down the normal blend factor (towards 0) and have current highlight with a larger blend; check [the color-pop example](https://github.com/jdtsmith/indent-bars/blob/main/examples.md#minimal-colorpop).
