### ISSUE TITLE
Feature: highlight block/scope

### ISSUE THREAD

**Issue by magthe** [jdtsmith/indent-bars#24]
A colleague pointed me to [indent-blankline](https://github.com/lukas-reineke/indent-blankline.nvim) for Neovim, and it has a rather cool feature in that it can highlight the current block/scope by using information from treesitter:

![indent-blankline](https://github.com/jdtsmith/indent-bars/assets/327270/8432d719-db2e-4c90-8b13-4c10e85be03a)

There are more examples on the project's GitHub page.

Maybe this is a worthy addition to _indent-bars_.

**Comment by jdtsmith** [comment]
I've thought of that; might be hard to do in a performant manner.  How does the user configure enclosing block level types?  It doesn't seem to use treesitter?

**Comment by jdtsmith** [comment]
Notes on how to implement:

- indent-bars uses face-remapping when the depth changes for ultra-fast current depth highlight.
- There is sadly no such thing as overlay-based or region-restricted face-remapping, or other way to "turn on" a latent face setting that lies dormant in the buffer (i.e. put there by font-lock).
- You'd therefore need to keep track of the containing treesit node's boundaries, and check if those buffer positions have changed since last invocation.
- You also need to check if the depth has changed.
- If _either_ has changed:
   1. replace the appropriate `-highlight` versions of the face for the last highlighted depth with their normal un-highlighted equivalents in the current region
   2. save the new region (if any)
   3. save the current depth
   4. replace all non`-highlight` versions in the (possibly new) region with their `-highlight` equivalents

Awkwardly, in addition to the usual `(next-single-property-change (point) 'face)` rigamarole, you must also check inside any `'display` strings in the region (tabs, blank lines), and perform the same face-swap operation in any that exist there.    If this sounds like so much work you should just throw away the formatting and redo it, you can't really use just `font-lock` for this, because that is optimized to update fonts on text changes, whereas this must run in a post-command-hook even after simple movements within the buffer. 

Not at all obvious how to do this well.

**Comment by magthe** [comment]
I'm pretty sure that something like [combobulate](https://github.com/mickeynp/combobulate) could offer a lot of insights into working with tree-sitter grammars for this.

I'm sorry I can't offer anything more detailed.

**Comment by jdtsmith** [comment]
No problem, those are mostly notes to myself.  Treesitter is not an issue, I can easily get the bounds of the method/function/if-block etc. at point (well, I'll make the user write a list of such block types of interest).  It's more a drawing problem with efficiently updating the faces as you move about.  I'll leave this open for a while as a tickler, to see if anyone has any ideas.

**Comment by jdtsmith** [comment]
v0.5 now includes tree-sitter based scope awareness, with full style configuration both in- and out-of-scope.  Give a try and let me know of any problems.
